// App/Angular/docker-demo-angular/src/app/persons/persons.component.ts
import { Component, OnInit } from '@angular/core';
import { PersonsService } from './persons.service';
import { PersonDto } from './person.model';

@Component({
  selector: 'app-persons',
  templateUrl: './persons.component.html',
  styleUrls: ['./persons.component.css'],
})
export class PersonsComponent implements OnInit {
  persons: PersonDto[] = [];

  constructor(private readonly personsService: PersonsService) {}

  ngOnInit(): void {
    this.personsService.getAllPersons().subscribe({
      next: (data) => (this.persons = data),
      error: (error) => console.error('Error fetching persons:', error),
    });
  }
}

<div>
  <h1>Personer</h1>
  <ul>
    <li *ngFor="let person of persons">
      {{ person.firstName }} {{ person.lastName }} - Age: {{ person.age }}
    </li>
  </ul>
</div>

// App/React/docker-demo-react/src/Persons.tsx
import React, { useState, useEffect } from "react";
import axios from "axios";

interface PersonDto {
  id: number;
  firstName: string;
  lastName: string;
  age: number;
}

const Persons: React.FC = () => {
  const [persons, setPersons] = useState<PersonDto[]>([]);

  useEffect(() => {
    const fetchPersons = async () => {
      try {
        const response = await axios.get(
          "http://localhost:23223/Person/getAllPersons"
        );
        setPersons(response.data);
      } catch (error) {
        console.error("Error fetching persons:", error);
      }
    };

    fetchPersons();
  }, []);

  return (
    <div>
      <h1>Personer</h1>
      <ul>
        {persons.map((person) => (
          <li key={person.id}>
            {person.firstName} {person.lastName} - Age: {person.age}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Persons;
