// App/Vue/docker-demo-vue/src/components/Persons.vue
<template>
  <div>
    <h1>Personer</h1>
    <ul>
      <li v-for="person in persons" :key="person.personID">
        {{ person.name }} {{ person.city }} - Age: {{ person.age }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from "vue";
import axios from "axios";

interface PersonDto {
  personID: number;
  name: string;
  city: string;
  age: number;
}

export default defineComponent({
  name: "PersonList",
  setup() {
    const persons = ref<PersonDto[]>([]);

    const fetchPersons = async () => {
      try {
        const response = await axios.get(
          "http://localhost:23223/Person/getAllPersons"
        );
        persons.value = response.data;
      } catch (error) {
        console.error("Error fetching persons:", error);
      }
    };

    onMounted(() => {
      fetchPersons();
    });

    return {
      persons,
    };
  },
});
</script>

<style scoped>
ul {
  background-color: aquamarine;
}
li {
  background-color: aliceblue;
}
li:hover {
  background-color: burlywood;
}
</style>

// App/React/docker-demo-react/src/Persons.tsx
import React, { useState, useEffect } from "react";
import axios from "axios";

interface PersonDto {
  personID: number;
  name: string;
  city: string;
  age: number;
}

const Persons: React.FC = () => {
  const [persons, setPersons] = useState<PersonDto[]>([]);

  useEffect(() => {
    const fetchPersons = async () => {
      try {
        const response = await axios.get(
          "http://localhost:23223/Person/getAllPersons"
        );
        setPersons(response.data);
      } catch (error) {
        console.error("Error fetching persons:", error);
      }
    };

    fetchPersons();
  }, []);

  return (
    <div>
      <h1>Personer</h1>
      <ul>
        {persons.map((person) => (
          <li key={person.personID}>
            {person.name} {person.city} - Age: {person.age}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Persons;
